openerp-atomfeed-service/src/main/resources/sql/db_migrations.xml
Adding pre-condition where ever it was missing.
=> Pankaj, Sidtharthan | Adding pre-condition where ever it was missing.

openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/client/AtomFeedClientHelper.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/client/FeedClientFactory.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/Jobs.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/OpenERPCustomerFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/OpenERPDrugFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/OpenERPLabFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/OpenERPSaleOrderFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/OpenElisSaleOrderFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/ReferenceDataFeedJob.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/job/SimpleFeedJob.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/client/OpenERPCustomerFeedIT.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/job/OpenERPDrugFeedJobTest.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/job/OpenERPLabFeedJobTest.java
Jobs enum now carry the urikey ref
=> BAH-768 | Refactored to remove unnecessary feeduri and feedname variable

openerp-atomfeed-service/pom.xml, pom.xml
…ting sync between elis and openmrs
=> BAH-1152|Buvaneswari|bahmni-erp-connect service, when running, is halting sync between elis and openmrs

.github/workflows/ci-v0.94.yml, .github/workflows/validate_pr.yml, README.md
Two workflows has been configured.
1. CI-v0.94 which triggers on push to master
2. Validate PR which triggers on Pull request to master and runs only unit tests.
=> BDI-14 | Configuring Github Actions for Docker Image build and publish

.github/workflows/ci.yml
Co-authored-by: swatigogia2020 <swati.gogia@thoughtworks.com>
=> BAH-1393 | Removed v0.94 from CI

.github/workflows/build_publish.yml, .github/workflows/validate_pr.yml, .gitignore, .mvn/wrapper/maven-wrapper.properties, README.md, mvnw, mvnw.cmd
1. Added Maven Wrapper
2. Updated README
=> Added. Maven Wrapper

.github/workflows/build_publish.yml, pom.xml
- Upgrades web-clients version to 0.94.3-SNAPSHOT
- Removed some obsolete repositories
=> BAH-2839| Upgrades web-clients version to 0.94.3

.github/workflows/build_publish.yml
Trigger auto deployment to Bahmni Standard Environment on successful completion of odoo-connect docker image
=> BAH-2889 | Trigger auto deployment to Bahmni Standard Environment

openerp-atomfeed-service/pom.xml, package/docker/scripts/run-liquibase.sh
JIRA -> [BAH-3264](https://bahmni.atlassian.net/browse/BAH-3264)
In this PR, the Postgresql JDBC driver version has been bumped so as to support `scram-sha-256` authentication method.
=> [Rahul] | BAH-3264 | Add. Bump JDBC Driver Version

pom.xml
Bump Spring Version 4.1.4.RELEASE to 4.2.0.RELEASE.
=> BAH-3270 | Add. Bump Spring 4.1 -> 4.2

openerp-atomfeed-service/pom.xml, package/docker/scripts/run-liquibase.sh, pom.xml
Bump Spring Version 4.2.0.RELEASE to 4.3.0.RELEASE, liquibase-core and liquibase-maven-plugin to 3.3.2
=> BAH-3270 | Add. Bump Spring 4.2->4.3

openerp-atomfeed-service/pom.xml, openerp-client/pom.xml, pom.xml
Bump Spring Version 5.0.0.RELEASE to 5.1.0.RELEASE
=> [Rahul] | BAH-3270 | Add. Bump Spring 5.0->5.1

pom.xml
Bump Spring Version 5.1.0.RELEASE to 5.2.0.RELEASE
=> [Rahul] | BAH-3270 | Add. Bump Spring 5.1->5.2

pom.xml
Bump Spring Version 5.2.0.RELEASE to 5.3.0
=> [Rahul] | BAH-3270 | Add. Bump Spring 5.2->5.3

openerp-atomfeed-service/pom.xml, openerp-client/pom.xml, pom.xml
In this PR, the following changes have been made : 
1. Undeclared Used Dependencies Added
2. Bumped Version of Certain Dependencies to Reduce Security Vulnerability
=> [Parvathy, Rahul] | Add. Undeclared Used Dependencies

openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/AtomfeedServiceConstants.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/OpenERPAtomFeedProperties.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/client/AtomFeedClientHelper.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/client/FeedClientFactory.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPCustomerServiceEventWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPDrugServiceEventWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPLabOrderTypeServiceEventWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPSaleOrderEventWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPSaleableResourceWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenElisSaleOrderEventWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/WorkerFactory.java, openerp-atomfeed-service/src/main/resources/jobs-context.xml, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/client/OpenERPCustomerFeedIT.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/event/OpenERPCustomerServiceEventWorkerTest.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/worker/OpenERPDrugServiceEventWorkerTest.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/worker/OpenERPLabOrderTypeServiceEventWorkerTest.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/worker/OpenERPSaleOrderEventWorkerIT.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/worker/OpenERPSaleableResourceWorkerTest.java, openerp-client/pom.xml, openerp-client/src/main/java/org/bahmni/openerp/web/client/strategy/OpenERPClientStrategy.java, openerp-client/src/main/java/org/bahmni/openerp/web/client/strategy/OpenERPContext.java, openerp-client/src/main/java/org/bahmni/openerp/web/client/strategy/implementation/OdooRESTClient.java, openerp-client/src/main/java/org/bahmni/openerp/web/client/strategy/implementation/OpenERPXMLClient.java, openerp-client/src/main/java/org/bahmni/openerp/web/http/client/RestClient.java, openerp-client/src/main/java/org/bahmni/openerp/web/http/client/XMLClient.java, pom.xml
Jira -> [BAH-3331](https://bahmni.atlassian.net/browse/BAH-3331)
In this PR, we implement the REST JSON Based Strategy. By implementing the RESTClient, we have successfully incorporated the REST-based strategy, adhering to the strategy design pattern. This foundational change enables the system to seamlessly transition between various strategies but also lays the groundwork for future enhancements.
Key Changes:
Integration of RESTClient: A new REST-based implementation strategy has been added, enriching the system's capabilities.
Activation of Create Drug Route: This enhancement empowers the system to make calls to Odoo and synchronize data effectively. The rest of the routes will be enabled with further PR's.
=> BAH-3331 | Add. Rest Client Implementation for Create Drug

openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/OpenERPAtomFeedProperties.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/domain/OpenMRSPersonAttributes.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPCustomerServiceEventWorker.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/event/OpenERPCustomerServiceEventWorkerTest.java, openerp-client/src/main/resources/request/template/rest_template.ftl
Jira -> [BAH-3235](https://bahmni.atlassian.net/browse/BAH-3235)
In this PR, we implement the REST JSON Based Strategy for Customer Sync. By implementing the RESTClient, we have successfully incorporated the REST-based strategy, adhering to the strategy design pattern. This foundational change enables the system to seamlessly transition between various strategies but also lays the groundwork for future enhancements.
=> BAH-3235 | Add. Rest Client Implementation for Create Customer

openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/OpenERPAtomFeedProperties.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/OpenERPSaleableResourceWorker.java, openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/worker/WorkerFactory.java, openerp-atomfeed-service/src/test/java/org/bahmni/feed/openerp/worker/OpenERPSaleableResourceWorkerTest.java
Jira -> [BAH-3303](https://bahmni.atlassian.net/browse/BAH-3303)
In this PR, we implement the REST JSON Based Strategy for Saleable Drug and Lab Test. By implementing the RESTClient, we have successfully incorporated the REST-based strategy, adhering to the strategy design pattern. This foundational change enables the system to seamlessly transition between various strategies but also lays the groundwork for future enhancements.
=> BAH-3303 | Add. Rest Client Implementation for Saleables

openerp-client/src/main/java/org/bahmni/openerp/web/client/strategy/implementation/OdooRESTClient.java, openerp-client/src/main/java/org/bahmni/openerp/web/http/client/RestClient.java
Jira -> [BAH-3374](https://bahmni.atlassian.net/browse/BAH-3374)
=> [BAH-3374 | Add. Session Cookies To REST Post Calls

openerp-atomfeed-service/src/main/java/org/bahmni/feed/openerp/domain/encounter/OpenERPOrders.java
JIRA -> [BAH-3738](https://bahmni.atlassian.net/browse/BAH-3738)
This PR handles the incorrect syncing of quantity for same drug ordered with different frequencies.
=> Parvathy | BAH-3738 | Fix. Handle Incorrect Syncing Of Quantity For Same Drug Orders

openerp-atomfeed-service/pom.xml
Reverts Bahmni/openerp-atomfeed-service#110
=> Revert "Deepthi M| BAH-3932|Updated the versions of postgres and liquibase to resolve the vulnerabilities"

.github/workflows/build_publish.yml, .github/workflows/validate_pr.yml, .travis.yml, README.md, package/docker/Dockerfile, pom.xml
JIRA -> [BAH-3987](https://bahmni.atlassian.net/browse/BAH-3987)
This PR aims to transition the Java version in the openerp-atomfeed-service repository from Java 8 to Java 11.
=> BAH-3987 | Add. Bump Java Version 8 -> 11

openerp-atomfeed-service/pom.xml, openerp-client/pom.xml, pom.xml
JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.
=> BAH-4097 | Add. Bump Version 0.94-SNAPSHOT -> 1.0
